AWSTemplateFormatVersion: "2010-09-09"
Description: Create SNS and SQS

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: "cloudwatch-practice-zhangtian"
        S3Key: "zipFile.zip"

      FunctionName: "zhangtian-SNS-practice"
      Handler: "index.run"
      Role: "arn:aws:iam::494526681395:role/for-aws-training"
      Runtime: "nodejs10.x"

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "Zhangtian-SNS-topic"
      Subscription:
        - Endpoint: "tizhang@thoughtworks.com"
          Protocol: "email"
        - Endpoint: !GetAtt SimpleSQS.Arn
          Protocol: "sqs"

  EventTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sns:Publish'
            Resource: '*'
      Topics:
        - !Ref SNSTopic

  SimpleSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "Zhangtian-practice-queue"
      MessageRetentionPeriod: 604800
      VisibilityTimeout: 300

  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Scheduled to trigger SNS every five minutes"
      Name: "zhangtian-trigger-SNS-event"
      RoleArn: "arn:aws:iam::494526681395:role/aws-practice-cloudwatch-event"
      ScheduleExpression: "rate(5 minutes)"
      State: "ENABLED"
      Targets:
        - Arn: !Ref "SNSTopic"
          Id: "TargetSNS"

  LambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt SimpleSQS.Arn
      FunctionName: !Ref LambdaFunction

  SampleSQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SimpleSQS
      PolicyDocument:
        Statement:
          - Action:
              - "sqs:SendMessage"
              - "sqs:ReceiveMessage"
              - "sqs:DeleteMessage"
              - "sqs:GetQueueAttributes"
            Effect: "Allow"
            Resource: !GetAtt SimpleSQS.Arn
            Principal: "*"
